name 'attributes'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures attributes'
long_description 'Installs/Configures attributes'
version '0.1.0'
